# The name of the logger to apply the filters to.
# In the message "[10:54:43] [main/INFO] [FML]: Replaced 1087 ore ingredients", the logger name is "FML".
"FML" = [
	{	# A prefix filter checks if a message starts with the specified string.
		type="prefix"
		filter="Unable to lookup"
	}
	{	type="contains"
		filter=".jar, however there is no signature matching that"
	}
	{	type="regex"
		filter="The world .* may have leaked.*"
	}
	{	type="regex"
		filter="Registry .*: Fixed minecraft:.* id mismatch.*"
	}
	{	type="prefix"
		filter="Automatically registered"
	}
	{	type="prefix"
		filter="Unable to find"
	}
	{	type="prefix"
		filter="Registry Item: Object did not get ID"
	}



]
# The root logger is the parent of all other Log4J loggers.
# It can be used to create global filters.
"root" = [
	{	# A "contains" filter checks if a message contains the specified string.
		type="equals"
		filter="########## GL ERROR ##########"
	}
	{	type="equals"
		filter="@ Post render"
	}
	{	type="equals"
		filter="1282: Invalid operation"
	}
]
"STDERR" = [
	{	type="regex"
		filter="[vazkii.patchouli.client.*"
	}
	{	type="prefix"
		filter="Patchouli failed"
	}
]
"VintageFix" = [
	{	type="prefix"
		filter="Error loading model block definition"
	}
]

"GregTech" = [
	{	type="prefix"
		filter="Invalid Recipe Found"
	}

]
"mixin" = [
	{	type="regex"
		filter="Catching .* java.lang.ClassNotFoundException: The specified class .* was not found .*"
	}

]
"scannable" = [{
	type="regex"
	filter=".*"
}]
"starmaker" = [{
	type="regex"
	filter=".*"
}]
"Food Spoiling" = [{
	type="regex"
	filter=".*"
}]
"bonsaitrees" = [{
	type="regex"
	filter=".*"
}]
"opencomputers" = [{
	type="regex"
	filter="Registering .*"
}]














