#Splash screen properties
#Sun Jul 19 12:23:49 GMT+07:00 2026
background=0xFFFFFF
bar=0x33DDDD
barBackground=0xFFFFFF
barBorder=0xBBBBBB
enabled=true
font=0x0
fontTexture=textures/font/ascii.png
forgeTexture=textures/null.png
logoOffset=0
memoryGood=0x88DD44
memoryLow=0xFF3333
memoryWarn=0xEEEE55
resourcePackPath=resourcepacks
rotate=false
showMemory=true
